build-test:
  needs: [ lint, unit-tests ]
  runs-on: ubuntu-24.04
  steps:
    - uses: actions/checkout@v4
    - run: docker build -t test-image ./server --file ./server/dockerfile
    - run: docker run -d --name app-server8000 -p 8000:8000 --restart unless-stopped test-image
    - run: sleep 20
    - run: docker ps -a
    - run: docker logs app-server8000
    - run: netstat -tuln | grep 8000 || true
    - run: curl --retry 3 --retry-delay 5 http://127.0.0.1:8000 || echo "Curl failed"
